"""
Pydantic v2 Data Models for Project AEGIS-AI.
Defines strict schemas for network telemetry, anomaly scores, MITRE mappings,
asset profiles, containment rules, incident cards, and agent thought events.
"""

from typing import List, Optional, Dict, Any
from datetime import datetime, timezone
from pydantic import BaseModel, Field
import uuid


# ──────────────────────────────────────────────────────────────────────────────
# Telemetry & Flow Models
# ──────────────────────────────────────────────────────────────────────────────

class NetworkFlowVector(BaseModel):
    """Represents a single network flow with 41 statistical features and metadata."""
    flow_id: str = Field(default_factory=lambda: f"FLOW-{uuid.uuid4().hex[:8].upper()}")
    src_ip: str = "0.0.0.0"
    dst_ip: str = "0.0.0.0"
    src_port: int = 0
    dst_port: int = 0
    protocol: str = "TCP"
    features: Dict[str, Any] = Field(default_factory=dict, description="Raw flow feature dict for extraction")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ──────────────────────────────────────────────────────────────────────────────
# Anomaly Scoring Models
# ──────────────────────────────────────────────────────────────────────────────

class AnomalyScoreResult(BaseModel):
    """Result of running a flow vector through the Isolation Forest perception engine."""
    flow_id: str
    bdi_score: float = Field(ge=0.0, le=1.0, description="Behavioral Deviation Index [0.0, 1.0]")
    is_anomaly: bool
    status: str  # NOMINAL | SUSPICIOUS | CRITICAL_ANOMALY
    raw_isolation_score: float = 0.0
    inference_ms: float = 0.0


# ──────────────────────────────────────────────────────────────────────────────
# MITRE ATT&CK Mapping Models
# ──────────────────────────────────────────────────────────────────────────────

class MitreMapping(BaseModel):
    """Represents a matched MITRE ATT&CK technique from the Threat Hunter agent."""
    technique_id: str  # e.g. "T1021.002"
    technique_name: str  # e.g. "SMB/Windows Admin Shares"
    tactic: str  # e.g. "Lateral Movement"
    description: str
    confidence: float = Field(ge=0.0, le=100.0, description="Confidence percentage")
    indicators_matched: List[str] = Field(default_factory=list)
    mitigation: str = ""


# ──────────────────────────────────────────────────────────────────────────────
# Asset & Topology Models
# ──────────────────────────────────────────────────────────────────────────────

class AssetProfile(BaseModel):
    """Represents a network asset from the internal subnet registry."""
    ip: str
    hostname: str
    owner_department: str
    criticality_level: str  # CRITICAL_TIER_1 | MEDIUM | LOW_TIER_3
    os_type: str
    mac_address: str = "UNKNOWN"
    subnet: str = "UNKNOWN"
    crown_jewel: bool = False


# ──────────────────────────────────────────────────────────────────────────────
# Containment Rule Models
# ──────────────────────────────────────────────────────────────────────────────

class ContainmentRules(BaseModel):
    """Platform-specific firewall containment rules generated by the Rule Agent."""
    iptables_rule: str
    cisco_acl: str
    powershell_command: str


# ──────────────────────────────────────────────────────────────────────────────
# Agent Thought Streaming Models
# ──────────────────────────────────────────────────────────────────────────────

class AgentThoughtEvent(BaseModel):
    """A single real-time thought event streamed from an agent to the SOC UI."""
    agent_name: str  # Supervisor | ThreatHunter | AssetInvestigator | RuleGenerator
    step_type: str  # THOUGHT | TOOL_CALL | TOOL_OUTPUT | SYNTHESIS | ERROR
    message: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = Field(default_factory=dict)


# ──────────────────────────────────────────────────────────────────────────────
# Incident Card (Unified Agent Output)
# ──────────────────────────────────────────────────────────────────────────────

class IncidentCard(BaseModel):
    """Unified synthesized incident card assembled by the Supervisor Agent.
    Contains the combined outputs from all sub-agents: MITRE mapping,
    asset blast radius, and containment rules.
    """
    incident_id: str = Field(default_factory=lambda: f"AEGIS-{uuid.uuid4().hex[:6].upper()}")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    bdi_score: float
    attacker_ip: str
    target_ip: str
    target_port: int
    protocol: str = "TCP"

    # Sub-agent outputs
    flow_analysis_summary: str = ""
    asset: Optional[AssetProfile] = None
    mitre_threat: Optional[MitreMapping] = None
    containment: Optional[ContainmentRules] = None

    # Reasoning trace
    agent_reasoning_trace: List[AgentThoughtEvent] = Field(default_factory=list)
    agent_reasoning_summary: str = ""

    # Status
    status: str = "PENDING_APPROVAL"  # PENDING_APPROVAL | CONTAINED | DISMISSED
    total_triage_ms: float = 0.0


# ──────────────────────────────────────────────────────────────────────────────
# Containment Approval Request (Human-in-the-Loop)
# ──────────────────────────────────────────────────────────────────────────────

class ContainmentApprovalRequest(BaseModel):
    """Request model for human-in-the-loop containment execution."""
    incident_id: str
    officer_token: str = "SOC-OFFICER-AUTH-TOKEN-DEMO"
    rule_type: str = "iptables"  # iptables | cisco | powershell
    approval_action: str = "APPROVE"  # APPROVE | REJECT
